CenterForOpenScience/angular-osf

src/assets/styles/overrides/table.scss
Changed table styling according to the Figma design
=> Fix(table-styles): Changed table styling

src/app/core/components/header/header.component.ts, src/app/core/components/request-access/request-access.component.ts, src/app/features/auth/services/auth.service.ts, src/app/features/project/analytics/analytics.component.html, src/app/features/project/contributors/contributors.component.html, src/app/features/project/registrations/registrations.component.html, src/app/features/project/settings/settings.component.html, src/app/features/project/wiki/wiki.component.html, src/app/features/registries/constants/default-steps.ts, src/app/features/registry/pages/registry-wiki/registry-wiki.component.html
=> fix(log-out): updated translations and log out

src/environments/environment.test-osf.ts
=> fix(recaptcha-key): update recaptcha key

src/app/features/registries/components/review/review.component.ts, src/app/features/registries/components/select-components-dialog/select-components-dialog.component.html
=> fix(draft): registries select component

src/app/shared/components/make-decision-dialog/make-decision-dialog.component.html, src/app/shared/components/make-decision-dialog/make-decision-dialog.component.ts
Fixed moderation process for already approved submission for the collections with pre-moderation workflow
=> Fix(collections-moderation): Fixed decision-making for approved projects

src/app/features/moderation/components/preprint-submission-item/preprint-submission-item.component.html, src/app/features/moderation/components/registry-submission-item/registry-submission-item.component.html, src/app/shared/components/resource-card/resource-card.component.html, src/app/shared/components/resource-card/resource-card.component.ts
…e card
- Ticket: [ANG-733, ANG-701]
=> Fix - Dates timezone problem and resource card opening

src/app/features/files/pages/file-detail/file-detail.component.ts, src/app/features/metadata/components/metadata-resource-information/metadata-resource-information.component.html, src/app/features/metadata/dialogs/edit-title-dialog/edit-title-dialog.component.html, src/app/features/metadata/dialogs/edit-title-dialog/edit-title-dialog.component.ts
=> fix(metadata): fixed metadata bugs

src/app/features/files/pages/files/files.component.ts, src/app/features/preprints/components/preprint-details/additional-info/additional-info.component.html, src/app/features/preprints/components/preprint-details/general-information/general-information.component.html, src/app/features/preprints/components/preprint-details/preprint-doi-section/preprint-doi-section.component.html, src/app/features/preprints/components/preprint-details/preprint-file-section/preprint-file-section.component.html, src/app/features/preprints/pages/preprint-details/preprint-details.component.html, src/styles/_common.scss
- Ticket: []
1. Fixed some preprint styles.
=> fix(preprint): fixed some styles

src/app/features/moderation/pages/registries-moderation/registries-moderation.component.ts, src/app/features/registries/pages/registries-landing/registries-landing.component.ts, src/app/features/registries/pages/registries-provider-search/registries-provider-search.component.ts, src/app/shared/stores/registration-provider/registration-provider.actions.ts, src/app/shared/stores/registration-provider/registration-provider.state.ts
=> Fix - Registry Discover search section

src/app/features/metadata/dialogs/contributors-dialog/contributors-dialog.component.html, src/app/features/metadata/metadata.component.ts, src/app/shared/components/resource-card/resource-card.component.html
- Ticket: [ANG-800]
1. Fixed bug.
=> fix(responsive): fixed bug

src/app/features/files/models/get-resource-short-info-response.model.ts, src/app/features/files/models/get-short-info-response.model.ts, src/app/features/metadata/dialogs/license-dialog/license-dialog.component.ts, src/app/features/metadata/mappers/metadata.mapper.ts, src/app/features/metadata/metadata.component.ts, src/app/features/metadata/models/metadata-json-api.model.ts, src/app/features/metadata/models/metadata.model.ts, src/app/features/metadata/services/metadata.service.ts, src/app/features/metadata/store/metadata.model.ts, src/app/features/metadata/store/metadata.state.ts, src/app/shared/mappers/identifiers.mapper.ts, src/app/shared/models/identifiers/identifier-json-api.model.ts, src/app/shared/services/custom-dialog.service.ts, src/app/shared/services/datacite/datacite.service.ts, src/app/shared/stores/contributors/contributors.selectors.ts
- Ticket: [ANG-818]
1. Fixed contributors on metadata page.
=> fix(metadata): fixed contributors bug and updated models

src/app/features/files/components/edit-file-metadata-dialog/edit-file-metadata-dialog.component.ts, src/app/features/project/overview/project-overview.component.html, src/app/features/project/overview/project-overview.component.ts, src/app/features/project/overview/store/project-overview.selectors.ts, src/app/shared/stores/wiki/wiki.state.ts
=> fix(wiki): fixed wiki bugs

src/app/features/collections/components/add-to-collection/project-metadata-step/project-metadata-step.component.html, src/app/features/collections/services/project-metadata-form.service.ts
Made tags optional in the add to collection stepper form
=> Fix(ang-898): Made tags optional

src/app/features/project/overview/components/add-component-dialog/add-component-dialog.component.html, src/app/features/project/overview/components/add-component-dialog/add-component-dialog.component.ts, src/app/shared/components/affiliated-institution-select/affiliated-institution-select.component.html
Fixed create components affiliations issue
=> Fix(ang-905): Fixed create component affiliations issue

src/app/features/registries/registries.routes.ts
=> Fix - ANG-932

src/app/features/preprints/components/stepper/preprints-metadata-step/preprints-metadata-step.component.html
=> [NIR] fix(ANG-621): fixed datepicker being of half length

src/app/features/preprints/components/stepper/author-assertion-step/author-assertions-step.component.html, src/app/features/preprints/components/stepper/author-assertion-step/author-assertions-step.component.ts, src/app/features/preprints/components/stepper/preprints-metadata-step/preprints-metadata-step.component.html
=> fix(preprints): fixed bug with width

src/app/features/registries/components/drafts/drafts.component.ts, src/app/features/registries/components/registries-metadata-step/registries-license/registries-license.component.ts, src/app/features/registries/services/licenses.service.ts, src/app/features/registries/store/registries.actions.ts
… based on project with license
- Ticket: [ANG-929]
=> Fix - License is a required field for all registrations, but can be submited without one.

src/app/shared/components/addons/storage-item-selector/storage-item-selector.component.html, src/app/shared/components/addons/storage-item-selector/storage-item-selector.component.ts
- Ticket: []
1. Fixed addons translation.
=> fix(translations): fixed addons translation

src/app/features/contributors/contributors.component.ts
=> fix(bug): fixed request access bug

src/app/features/registry/components/registry-revisions/registry-revisions.component.ts, src/app/features/registry/components/registry-statuses/registry-statuses.component.html, src/app/features/registry/components/registry-statuses/registry-statuses.component.ts, src/app/shared/constants/registration-statuses.ts, src/app/shared/enums/registry-status.enum.ts, src/app/shared/mappers/registration/map-registry-status.mapper.ts, src/assets/i18n/en.json
- Ticket: [ANG-972]
1. Fixed registry overview bug.
=> fix(registry-statuses): fixed statuses for registry

src/app/features/preprints/pages/preprint-details/preprint-details.component.ts
=> Fix - Showing error message after create new preprint version conflict
